### ISSUE TITLE
Alignment setting

### ISSUE THREAD

**Issue by Kishimotovn** [crescentflare/UniLayout#1]
Hi, 
Is there any way that I can set the horizontal alignment of subview?
For example, I want to align textViews based on their baseline or top property
Thanks

**Comment by crescentflare** [comment]
Hi,
To align subviews you can use the gravity values of the layoutProperties within a UniTextView (or any other view implementing the UniLayoutView protocol). Additionally, the view must be a subview of a UniLayout container (such as UniLinearContainer). For example, a horizontalGravity value of 0.5, centers the view horizontally.
